{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "422bd41e-9fe5-4135-b5c4-97d22df8e6ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fetched 50 videos in this batch\n",
      "Fetched 50 videos in this batch\n",
      "\n",
      "Sample of Top 5 Trending Videos:\n",
      "Title: Jack Black - Steve's Lava Chicken (Official Music Video) | A Minecraft Movie Soundtrack | WaterTower, Channel: WaterTower Music, Views: 577,784\n",
      "Title: Murderbot — Official Trailer | Apple TV+, Channel: Apple TV, Views: 1,284,594\n",
      "Title: Mario Kart Should Cost More, Channel: videogamedunkey, Views: 1,291,922\n",
      "Title: HIGHLIGHTS - Arsenal vs Real Madrid | UEFA Champions League - 4tos Final 24/25 | TUDN, Channel: TUDN USA, Views: 1,086,567\n",
      "Title: He was Attacking Everyone, Then I Found Out Why 🥺, Channel: Rocky Kanaka, Views: 494,601\n",
      "\n",
      "Data saved to trending_videos_20250410_131309.xlsx with 100 rows\n",
      "Waiting 1 hour for next run...\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "YouTube Trending Video Analytics (Automated)\n",
    "Fetches top 100 trending videos globally every hour and saves to Excel.\n",
    "Author: Supriya Sonone - April 2025\n",
    "\"\"\"\n",
    "\n",
    "from googleapiclient.discovery import build\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "import time\n",
    "\n",
    "# Configuration\n",
    "API_KEY = \"API_key\" \n",
    "TARGET_VIDEOS = 100\n",
    "REGION_CODE = None\n",
    "\n",
    "youtube = build(\"youtube\", \"v3\", developerKey=API_KEY)\n",
    "\n",
    "def get_subscribers(channel_id):\n",
    "    \"\"\"Fetch subscriber count for a given channel ID.\"\"\"\n",
    "    try:\n",
    "        request = youtube.channels().list(part=\"statistics\", id=channel_id)\n",
    "        response = request.execute()\n",
    "        return int(response[\"items\"][0][\"statistics\"][\"subscriberCount\"]) if response[\"items\"] else 0\n",
    "    except Exception as e:\n",
    "        print(f\"Error fetching subscribers for channel {channel_id}: {e}\")\n",
    "        return 0\n",
    "\n",
    "def fetch_trending_videos():\n",
    "    \"\"\"Fetch top 100 trending videos with details.\"\"\"\n",
    "    videos_data = []\n",
    "    max_results_per_call = 50\n",
    "    page_token = None\n",
    "\n",
    "    try:\n",
    "        while len(videos_data) < TARGET_VIDEOS:\n",
    "            request = youtube.videos().list(\n",
    "                part=\"snippet,statistics,contentDetails\",\n",
    "                chart=\"mostPopular\",\n",
    "                regionCode=REGION_CODE,\n",
    "                maxResults=max_results_per_call,\n",
    "                pageToken=page_token\n",
    "            )\n",
    "            response = request.execute()\n",
    "            print(f\"Fetched {len(response['items'])} videos in this batch\")\n",
    "\n",
    "            for video in response[\"items\"]:\n",
    "                videos_data.append({\n",
    "                    \"Video Name\": video[\"snippet\"][\"title\"],\n",
    "                    \"Views\": int(video[\"statistics\"][\"viewCount\"]),\n",
    "                    \"Likes\": int(video[\"statistics\"].get(\"likeCount\", 0)),\n",
    "                    \"Channel Name\": video[\"snippet\"][\"channelTitle\"],\n",
    "                    \"Post Date\": video[\"snippet\"][\"publishedAt\"],\n",
    "                    \"Duration\": video[\"contentDetails\"][\"duration\"],\n",
    "                    \"Subscribers\": get_subscribers(video[\"snippet\"][\"channelId\"]),\n",
    "                    \"Description\": video[\"snippet\"][\"description\"],\n",
    "                    \"Category\": video[\"snippet\"][\"categoryId\"]\n",
    "                })\n",
    "\n",
    "            page_token = response.get(\"nextPageToken\")\n",
    "            if not page_token or len(videos_data) >= TARGET_VIDEOS:\n",
    "                break\n",
    "\n",
    "        return videos_data[:TARGET_VIDEOS]\n",
    "    except Exception as e:\n",
    "        print(f\"Error fetching data: {e}\")\n",
    "        return []\n",
    "\n",
    "# Automation loop\n",
    "while True:\n",
    "    videos_data = fetch_trending_videos()\n",
    "    if videos_data:\n",
    "        print(\"\\nSample of Top 5 Trending Videos:\")\n",
    "        for video in videos_data[:5]:\n",
    "            print(f\"Title: {video['Video Name']}, Channel: {video['Channel Name']}, Views: {video['Views']:,}\")\n",
    "        \n",
    "        timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        filename = f\"trending_videos_{timestamp}.xlsx\"\n",
    "        df = pd.DataFrame(videos_data)\n",
    "        df.to_excel(filename, index=False)\n",
    "        print(f\"\\nData saved to {filename} with {len(videos_data)} rows\")\n",
    "    else:\n",
    "        print(\"No data fetched this run.\")\n",
    "\n",
    "    print(\"Waiting 1 hour for next run...\")\n",
    "    time.sleep(3600)  # 3600 seconds = 1 hour"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
